import turtle

turtle.color("red")
(turtle.right(90))
turtle.forward(100)
(turtle.left(90))
turtle.forward(200)
(turtle.right(90))
turtle.forward(100)

turtle.penup()
turtle.goto(200,0)
turtle.pendown()
turtle.color("red")
(turtle.right(90))
turtle.forward(100)
(turtle.left(90))
turtle.forward(200)
(turtle.right(90))
turtle.forward(100)
turtle.hideturtle()
turtle.done()
